# Generated by Django 5.2.6 on 2026-09-09 07:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_filename', models.CharField(max_length=255)),
                ('source_file', models.FileField(upload_to='catalogues/%Y/%m/%d/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('completed_errors', 'Completed with errors'), ('failed', 'Failed')], db_index=True, default='pending', max_length=30)),
                ('total_products', models.PositiveIntegerField(default=0)),
                ('processed_products', models.PositiveIntegerField(default=0)),
                ('successful_products', models.PositiveIntegerField(default=0)),
                ('failed_products', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='TaxonomyCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taxonomy_id', models.CharField(max_length=120, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('full_path', models.CharField(db_index=True, max_length=1000)),
                ('parent_path', models.CharField(blank=True, max_length=1000)),
                ('keywords', models.TextField(blank=True)),
                ('attributes', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['full_path'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=255)),
                ('model_number', models.CharField(blank=True, max_length=255)),
                ('title', models.CharField(max_length=1000)),
                ('description', models.TextField(blank=True)),
                ('product_type', models.CharField(blank=True, max_length=500)),
                ('brand', models.CharField(blank=True, max_length=255)),
                ('color', models.CharField(blank=True, max_length=255)),
                ('material', models.CharField(blank=True, max_length=500)),
                ('image_urls', models.JSONField(blank=True, default=list)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('alternatives', models.JSONField(blank=True, default=list)),
                ('detected_attributes', models.JSONField(blank=True, default=dict)),
                ('requires_review', models.BooleanField(db_index=True, default=False)),
                ('approved', models.BooleanField(db_index=True, default=False)),
                ('processing_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='classifier.importbatch')),
                ('predicted_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='predictions', to='classifier.taxonomycategory')),
            ],
        ),
        migrations.CreateModel(
            name='ClassificationAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=50)),
                ('old_category', models.CharField(blank=True, max_length=1000)),
                ('new_category', models.CharField(blank=True, max_length=1000)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_events', to='classifier.product')),
            ],
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['batch', 'processing_status'], name='classifier__batch_i_3ae541_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['batch', 'requires_review'], name='classifier__batch_i_16eed3_idx'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(fields=('batch', 'external_id'), name='unique_product_per_batch'),
        ),
    ]
